name: train-model
on: [pull_request]
jobs:
    train-model:
      runs-on: ubuntu-latest

      ##das ist der zweite Methode, anstelle davon kann den Zeile mit # verwenden, das geht davon raus das BAUMMETHODEN der working directory ist.
      defaults:
        run:
          working-directory: baummethoden/src/models/

      steps:
        - uses: actions/checkout@v2
        - name: set up python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8.5'

        - name: Install dependencies
          run: pip install -r ../../requirements.txt
          #run: pip install -r baummethoden/requirements.txt
        - name: Train model
          #run: python baummethoden/src/models/train.py
          run: python train.py

        - name: Archive production artifacts
          uses: actions/upload-artifact@v2
          with:
            name: classification_model.pickle
            path: baummethoden/models/classification_model.pickle 
           # path: ../../models/classification_model.pickle 

          