name: train-model
on: [pull_request]
jobs:
    train-model:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: set up python
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'
        - name: Install dependencies
          run: pip install -r baummethoden/requirements.text
        - name: Train model
          run: python baummethoden/src/models/train.py